# Generated by Django 5.0.1 on 2024-01-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protests', '0002_demonstration_protest_image_protest_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demonstration',
        ),
    ]
