# Generated by Django 5.0.1 on 2024-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protests', '0003_delete_demonstration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
